факториал
js-tasks-ru/jsbasic-20210520_anton851 pull request #2
Opened 2021-05-29 20:26 UTC by Antonb5r

2021-06-09 10:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-06-09 10:36 UTC, koalex requested changes

2021-06-09 10:36 UTC, koalex commented on 1-module/1-task/index.js
> +  alert(factorial(0));
`alert`-ы надо удалить

2021-06-09 10:36 UTC, koalex commented on 1-module/3-task/index.js
> +  return str[0].toUpperCase() + str.slice(1);
Лучше использовать `str.charAt(0).toUpperCase()`

2021-06-10 09:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-10 09:43 UTC, koalex requested changes

2021-06-10 09:43 UTC, koalex commented on 2-module/1-task/index.js
> +alert( sumSalaries(salaries) );
Нужно удалить этот `alert`

2021-06-11 07:35 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-06-14 17:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-06-14 17:36 UTC, koalex approved these changes

2021-06-14 17:36 UTC, koalex commented on 1-module/1-task/index.js
> +  factorial(0);
строки 4-8 лишние

2021-06-14 17:38 UTC, merged